In [4]:
import pandas as pd

#outside of folder because file is too large to upload to github
#use raw string because of unicode error otherwise
data = pd.read_csv(r"C:\Users\gabri\INST414\Crime_Data_from_2020_to_Present.csv", index_col="DR_NO")

In [5]:
data

,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
DR_NO,,,,,,,,,,,,,,,,,,,,,
190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,NaN,...,AA,Adult Arrest,510.0,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,34.0375,-118.3506
200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,1822 1402 0344,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,0344 1251,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),0325 1501,...,IC,Invest Cont,343.0,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,34.1576,-118.4387
200412582,09/09/2020 12:00:00 AM,09/09/2020 12:00:00 AM,630,4,Hollenbeck,413,1,510,VEHICLE - STOLEN,NaN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,200 E AVENUE 28,NaN,34.0820,-118.2130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250304214,02/23/2025 12:00:00 AM,02/21/2025 12:00:00 AM,1530,3,Southwest,358,1,510,VEHICLE - STOLEN,NaN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,3600 MCCLINTOCK AV,NaN,34.0212,-118.2895
250304203,02/20/2025 12:00:00 AM,02/13/2025 12:00:00 AM,2100,3,Southwest,325,1,522,"VEHICLE, STOLEN - OTHER (MOTORIZED SCOOTERS, B...",NaN,...,IC,Invest Cont,522.0,NaN,NaN,NaN,2600 ELLENDALE PL,NaN,34.0307,-118.2923
250504051,01/14/2025 12:00:00 AM,01/14/2025 12:00:00 AM,1250,5,Harbor,509,1,210,ROBBERY,1822 0344 1259,...,IC,Invest Cont,210.0,NaN,NaN,NaN,24300 WESTERN AV,NaN,33.8046,-118.3074
251604136,02/27/2025 12:00:00 AM,02/27/2025 12:00:00 AM,1550,16,Foothill,1664,1,510,VEHICLE - STOLEN,NaN,...,AA,Adult Arrest,510.0,NaN,NaN,NaN,11900 SHELDON ST,NaN,34.2404,-118.3922
251904210,03/25/2025 12:00:00 AM,03/25/2025 12:00:00 AM,1235,19,Mission,1944,2,850,INDECENT EXPOSURE,0529 2024 1815 0913,...,IC,Invest Cont,850.0,NaN,NaN,NaN,11100 OMELVENY AV,NaN,34.2722,-118.4417

data I want to keep from this:
time occ - will have to manually change to early morning, morning, mid-day, afternoon, evening, night 
area - dummies
crm cd - crime code - need dummies
mocodes - dummies
status - dummies
vict_sex - dumies
vict_descent - dummies
premis cd - dummies
weapon used code - dummies

In [10]:
data['hour'] = data['TIME OCC'] // 100
data['minute'] = data["TIME OCC"] % 100

data['total_minutes'] = data['hour'] * 60 + data['minute']

def get_time_of_day(minutes):
    if 300 <= minutes < 720:
        return 'morning'
    if 720 <= minutes < 1020:
        return 'afternoon'
    if 1020 <= minutes < 1260:
        return 'evening'
    else:
        return 'night'

data['time_of_day'] = data['total_minutes'].apply(get_time_of_day)

def get_age_range(age):
    if 0 <= age < 13:
        return 'child'
    if 13 <= age < 18:
        return 'teenager'
    if 18 <= age < 27:
        return 'young adult'
    if 27 <= age < 65:
        return 'adult'
    else:
        return 'senior'
    
data['vict age range'] = data['Vict Age'].apply(get_age_range)
data

,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,...,LOCATION,Cross Street,LAT,LON,hour,minute,total_minutes,time_of_day,age_range,vict age range
DR_NO,,,,,,,,,,,,,,,,,,,,,
190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,NaN,...,1900 S LONGWOOD AV,NaN,34.0375,-118.3506,21,30,1290,night,child,child
200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,1822 1402 0344,...,1000 S FLOWER ST,NaN,34.0444,-118.2628,18,0,1080,evening,adult,adult
200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,0344 1251,...,1400 W 37TH ST,NaN,34.0210,-118.3002,17,0,1020,evening,young adult,young adult
200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),0325 1501,...,14000 RIVERSIDE DR,NaN,34.1576,-118.4387,20,37,1237,evening,young adult,young adult
200412582,09/09/2020 12:00:00 AM,09/09/2020 12:00:00 AM,630,4,Hollenbeck,413,1,510,VEHICLE - STOLEN,NaN,...,200 E AVENUE 28,NaN,34.0820,-118.2130,6,30,390,morning,child,child
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250304214,02/23/2025 12:00:00 AM,02/21/2025 12:00:00 AM,1530,3,Southwest,358,1,510,VEHICLE - STOLEN,NaN,...,3600 MCCLINTOCK AV,NaN,34.0212,-118.2895,15,30,930,afternoon,child,child
250304203,02/20/2025 12:00:00 AM,02/13/2025 12:00:00 AM,2100,3,Southwest,325,1,522,"VEHICLE, STOLEN - OTHER (MOTORIZED SCOOTERS, B...",NaN,...,2600 ELLENDALE PL,NaN,34.0307,-118.2923,21,0,1260,night,child,child
250504051,01/14/2025 12:00:00 AM,01/14/2025 12:00:00 AM,1250,5,Harbor,509,1,210,ROBBERY,1822 0344 1259,...,24300 WESTERN AV,NaN,33.8046,-118.3074,12,50,770,afternoon,teenager,teenager
251604136,02/27/2025 12:00:00 AM,02/27/2025 12:00:00 AM,1550,16,Foothill,1664,1,510,VEHICLE - STOLEN,NaN,...,11900 SHELDON ST,NaN,34.2404,-118.3922,15,50,950,afternoon,child,child
251904210,03/25/2025 12:00:00 AM,03/25/2025 12:00:00 AM,1235,19,Mission,1944,2,850,INDECENT EXPOSURE,0529 2024 1815 0913,...,11100 OMELVENY AV,NaN,34.2722,-118.4417,12,35,755,afternoon,adult,adult

In [ ]:
#problem - took 15 minutes to process without any output, therefore to fix need to limit to just 2025 entries 
column_names = ["AREA", "time_of_day", "Crm Cd", "Mocodes", "vict age range", "Vict Sex", "Vict Descent", "Premis Cd", "Weapon Used Cd", "Status"]

dummies_to_concat = []

for column in column_names:
    dummies = data[f'{column}'].astype(str).str.get_dummies(sep=' ')
    dummies_to_concat.append(dummies)

encoded = pd.concat([data] + dummies_to_concat, axis=1)
encoded

: